### ISSUE TITLE
expresselrs configurator 1,5,0

### ISSUE THREAD

**Issue by Eg681** [ExpressLRS/repartitioner#1]
I've tried everything to build and build and flash but always the same messages please advise on this issue, I'm using a hp laptop running windows 10 I cant build much less build and flash using any of the methods. this is my build log. Thanks  
[ExpressLRSBuildLog_20220917205929019.txt](https://github.com/pkendall64/repartitioner/files/9592652/ExpressLRSBuildLog_20220917205929019.txt)

**Comment by pkendall64** [comment]
This is the issue tracker for the `repartitioner`, if you are having issues with the ExpressLRS configurator I suggest you join the ExpressLRS discord server and ask for help in the #help-and-support channel.
If you are trying to build the repartitioner to try to flash a device given the 'Bad Size Given' error then you really only need to download the binary from the release section here on github.

**Comment by Eg681** [comment]
Thanks for reply, I'm not sure if this problem is the configurator as you can see in the log there is no bad size given error, messages I get is platformio error and telling me to turn off firewall security which I have done. I have joined the discord and just hoping for some advise. I have twice tried older versions of the configurator but still same failed to build and same messages, just guessing at this point. thanks again. [ExpressLRSBuildLog_20220917205929019.txt](https://github.com/pkendall64/repartitioner/files/9592652/ExpressLRSBuildLog_20220917205929019.txt)
