### ISSUE TITLE
Force Update

### ISSUE THREAD

**Issue by FNTONN** [ExpressLRS/repartitioner#3]
I'm getting an error when updating my HM Express LRS 2.4ghz TX 
![image](https://user-images.githubusercontent.com/55706351/200699305-22400989-bff7-481c-96cd-a58f2a3d39ad.png)
Not sure why its happening

**Comment by xxchris82xx** [comment]
Same identical issue here, Happymodel Slim Pro Module on my X-Lite Pro.

any fix?

**Comment by pkendall64** [comment]
Retry via wifi and if it does not work, then flash via USB.
There really isn't any other option.
