### ISSUE TITLE
RX bricked after flashing repartitioner

### ISSUE THREAD

**Issue by georgipeev** [ExpressLRS/repartitioner#6]
I was getting the "Not Enough Space" error when trying to install ELRS 3.1.2 on my brand new Flywoo Explorer LR4 O3 with the Flywoo EL24P 2400 RX, so I found this solution and successfully flashed the repartitioner.bin, waited for a very long time, unpowered and powered back on. After that, the RX is fully bricked - it has no WiFi capabilities (not joining my home network as it did before, not making a network of its own), and I have no way to flash ELRS on it unless I do the fairly convoluted unbricking procedure that involves soldering.

**Comment by pkendall64** [comment]
You did not read the instructions. It is only for TX modules, i.e. ESP32 not ESP8285.
