### ISSUE TITLE
Not enough data uploaded

### ISSUE THREAD

**Issue by twidgit** [ExpressLRS/repartitioner#7]
I'm trying to flash 3.2.0 to my TX16S V2 with ELRS and it won't flash the repartitioner.  I get the alert: Not enough data uploaded even though I press "flash anyway"

**Comment by TomEderer** [comment]
Same issue here!

**Comment by tprelog** [comment]
I had the same issue on Happy Model Slim Pro

**Comment by pkendall64** [comment]
If all else fails, then flashing via the USB is the way to recover

**Comment by tprelog** [comment]
Got ExpreaaLRS updated, but I don't think I got the repartitioner to work.

I started with USB before switching to WiFi, but I was getting the following error with repartitioner (and ExpressLRS 3.2.1)

```
Failed to connect to ESP32: No serial data received
```

I was able to flash ExpressLRS 2.5.2 successfully over wifi, then ExpressLRS 3.2.1 flashed without issue as well - I assume I was doing something wrong the first time around :shrug: 

Anyways, it's working now - Sorry for the noise

**Comment by Trahht** [comment]
I tried to update 3.2.1 firmware for elrs micro 1w module. But now the module has been suspended, the oled screen is not displayed. Is there any way to fix it?

**Comment by pkendall64** [comment]
> I tried to update 3.2.1 firmware for elrs micro 1w module. But now the module has been suspended, the oled screen is not displayed. Is there any way to fix it?

Yes, flash it using the USB. Follow the instructions on https://www.expresslrs.org/quick-start/transmitters/betafpv2400/#via-uart
