### ISSUE TITLE
ELRS reciever bricked.

### ISSUE THREAD

**Issue by Jeanbonblanc** [ExpressLRS/repartitioner#8]
Well, as the title states, i made a mistake getting the file from another platform with no warning about recievers and flashed my reciever.

Ok it's bricked, and i need FTDI to unbrick it, BUT, it's an integrated reiever via UART.

Any info on how tyo unbrick that?

Ty

**Comment by pkendall64** [comment]
You can use betaflight passthrough to recover. You will need to get the ESP8285 chip into bootloader mode and there should be a button to enable that. You would be best asking on the discord server in the #help-and-support channel
You would also need to provide more information i.e. what flight controller it it etc.
